### ISSUE TITLE
Recurrent poster printing issue

### ISSUE THREAD

**Issue by nrybowski** [UCL-INMA/ICTEAMposter#1]
There is a recurrent issue when printing posters from this template via the UCLouvain poster printing service.

The paper-based printer refuses printing the lines defined here:

https://github.com/UCL-INMA/ICTEAMposter/blob/66b1370c243e69c6f95a232780d682151ea34ac2/beamerthemeICTEAMposter.sty#L193-L196

There are two quick fixes: printing the poster on the cardboard-based printer or comment the lines shown above to print on the paper-based printer.

A long term solution should be found. Maybe by exporting the tikzpicture as an image / pdf then import it back in the template?

**Comment by blegat** [comment]
I wasn't aware of this issue. Note sure what's the root cause, let me know if exporting as an image helps.

**Comment by pascalmaes** [comment]
A search on "Latex tikzpicture pdf printing problem" shows that we're not the only ones with this problem : https://tex.stackexchange.com/questions/283540/xelatex-with-tikz-external-library-produces-pdfs-of-wrong-size

Workaround : 

```
    \includegraphics[width=\textwidth]{line-block.eps}
%    \begin{tikzpicture}[remember picture,overlay]
%      \shade [inner color=UCLouvainBleuGris, outer color=white]
%      (0,0) rectangle (\textwidth,0.3cm);
%    \end{tikzpicture}

```

[line-block.eps.zip](https://github.com/UCL-INMA/ICTEAMposter/files/14318252/line-block.eps.zip)
